spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste
    username: postgres
    password: "0325"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

  flyway:
    enabled: false